const {test}=require('node:test');const assert=require('node:assert/strict');const {deliverCommunityMessage}=require('../lib/delivery');
const now=Date.now(),event={chatId:'thread',messageId:'reply',senderId:'B',createdAt:now};
function harness(){const claimed=new Set(),sent=[],removed=[];const d={chat:async()=>({participants:['A','B'],postId:'post'}),enabled:async()=>true,blocked:async()=>false,devices:async()=>[{id:'one',token:'valid',enabled:true,updatedAt:now}],claim:async id=>{if(claimed.has(id))return false;claimed.add(id);return true;},send:async(token,data)=>sent.push({token,data}),finish:async()=>{},removeToken:async(...v)=>removed.push(v)};return {d,sent,removed};}
test('B replies: A receives generic data; no text or sender name is transmitted',async()=>{const h=harness();await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,1);assert.equal(h.sent[0].data.recipientUid,'A');assert.deepEqual(Object.keys(h.sent[0].data).sort(),['chatId','deliveryId','kind','messageId','postId','recipientUid']);});
test('concurrent retries and repeated event never duplicate delivery',async()=>{const h=harness();await Promise.all([deliverCommunityMessage(h.d,event,now),deliverCommunityMessage(h.d,event,now)]);await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,1);});
test('self and non-participant are excluded',async()=>{const h=harness();h.d.chat=async()=>({participants:['B','B'],postId:'post'});await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,0);h.d.chat=async()=>({participants:['A','C'],postId:'post'});await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,0);});
test('disabled preference, blocked user and device toggle suppress delivery',async()=>{for(const mode of ['pref','block','device']){const h=harness();if(mode==='pref')h.d.enabled=async()=>false;if(mode==='block')h.d.blocked=async()=>true;if(mode==='device')h.d.devices=async()=>[{id:'d',token:'t',enabled:false,updatedAt:now}];await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,0);}});
test('multiple devices each get one logical notification',async()=>{const h=harness();h.d.devices=async()=>['one','two'].map(id=>({id,token:id,enabled:true,updatedAt:now}));await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,2);assert.notEqual(h.sent[0].data.deliveryId,h.sent[1].data.deliveryId);});
test('invalid token cleaned; other device still receives',async()=>{const h=harness();h.d.devices=async()=>['bad','ok'].map(id=>({id,token:id,enabled:true,updatedAt:now}));h.d.send=async(token,data)=>{if(token==='bad')throw {code:'messaging/registration-token-not-registered'};h.sent.push({token,data});};await deliverCommunityMessage(h.d,event,now);assert.deepEqual(h.removed,[['A','bad','bad']]);assert.equal(h.sent.length,1);});
test('old event and stale token do not send',async()=>{const h=harness();await deliverCommunityMessage(h.d,{...event,createdAt:now-2*86400000},now);h.d.devices=async()=>[{id:'one',token:'valid',enabled:true,updatedAt:now-31*86400000}];await deliverCommunityMessage(h.d,event,now);assert.equal(h.sent.length,0);});
test('ambiguous transport failure is not retried and cannot duplicate',async()=>{const h=harness();let attempts=0;h.d.send=async()=>{attempts++;throw Error('network');};await deliverCommunityMessage(h.d,event,now);await deliverCommunityMessage(h.d,event,now);assert.equal(attempts,1);});
