import {test,expect,type Page} from '@playwright/test';
// Controlled browser bridge: verifies React lifecycle, not physical Android delivery.
async function fixture(page:Page,mode='guide',language='pt'){
 await page.route(/(firestore|identitytoolkit|securetoken)\.googleapis\.com/,r=>r.abort());
 await page.addInitScript(({language})=>{localStorage.setItem('confia_language',language);const w=window as any;w.noticeInfo={deviceId:'test',permission:false,permissionState:'notRequested',communityChannel:true,reminderChannel:true};w.openedSettings=0;w.prompted=0;w.appListeners=[];w.androidBridge={};w.Capacitor={PluginHeaders:[{name:'ConfiaDevice',methods:['info','configure','widget','token','requestNoticePermission','openNoticeSettings','pinWidget'].map(name=>({name,rtype:'promise'}))},{name:'App',methods:[{name:'addListener',rtype:'callback'},{name:'removeListener',rtype:'promise'}]}],nativePromise:async(plugin:string,method:string)=>{if(method==='info')return structuredClone(w.noticeInfo);if(method==='openNoticeSettings'){w.openedSettings++;return;}if(method==='requestNoticePermission'){w.prompted++;return {granted:w.noticeInfo.permission};}return {};},nativeCallback:(plugin:string,method:string,options:any,callback:any)=>{if(plugin==='App')w.appListeners.push(callback);return 'test-listener';}};},{language});
 await page.route('**/__confia-test',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"/></head><body style="margin:0"><div id="root"></div><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module">import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';const {createRoot}=ReactDOM;import '/src/i18n/index.ts';import '/src/index.css';import Settings from '/src/components/NotificationSettings.tsx';import Zen from '/src/components/ZenRelease/ZenReleaseExperience.tsx';window.unmount=()=>root.unmount();const root=createRoot(document.getElementById('root'));root.render(React.createElement(${mode==='guide'?'Settings':'Zen'},{durationSeconds:300,onDone:()=>root.unmount()}));</script></body></html>`}));
 await page.goto('http://127.0.0.1:3000/__confia-test');
}
test('guide: never requested, denied, settings opened only on tap and return refreshes channel state',async({page})=>{await fixture(page);await page.getByRole('button',{name:'Informações sobre Respostas da Comunidade',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByText('Ainda não configurado',{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).openedSettings)).toBe(0);await page.evaluate(()=>{(window as any).noticeInfo={deviceId:'test',permission:false,permissionState:'denied'};window.dispatchEvent(new Event('focus'));});await expect(dialog.getByText('Não permitidas',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Abrir definições do telemóvel',exact:true}).click();expect(await page.evaluate(()=>(window as any).openedSettings)).toBe(1);await page.evaluate(()=>{const w=window as any;w.noticeInfo={deviceId:'test',permission:true,permissionState:'granted',communityChannel:true};w.appListeners.forEach((cb:any)=>cb({isActive:true}));});await expect(dialog.getByText('Permitidas',{exact:true})).toBeVisible();await expect(dialog.getByText('Esta opção ainda está desligada na CONFIA.',{exact:true})).toBeVisible();await page.evaluate(()=>{const w=window as any;w.noticeInfo.communityChannel=false;window.dispatchEvent(new Event('focus'));});await expect(dialog.getByText('Não permitidas',{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).prompted)).toBe(0);
 await dialog.getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('switch',{name:'Respostas da Comunidade',exact:true}).click();expect(await page.evaluate(()=>(window as any).prompted)).toBe(0);await page.evaluate(()=>{(window as any).noticeInfo.communityChannel=true;});await page.getByRole('button',{name:'Permitir',exact:true}).click();await expect(page.getByRole('switch',{name:'Respostas da Comunidade',exact:true})).toBeChecked();await page.getByRole('button',{name:'Informações sobre Respostas da Comunidade',exact:true}).click();await expect(dialog.getByText('Está tudo preparado.',{exact:false})).toBeVisible();await page.evaluate(()=>{(window as any).noticeInfo.permission=false;window.dispatchEvent(new Event('focus'));});await expect(dialog.getByText('Esta opção está ativa na CONFIA, mas as notificações estão bloqueadas no Android.',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Corrigir nas definições',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).prompted)).toBe(1);await page.screenshot({path:'/tmp/confia-notice-guide.png'});
});
for(const [language,title,without,release,question,same]of [['pt','Deixa ir','Usar sem microfone','Libertar um pouco','Como estou agora','Igual'],['en','Let go','Use without microphone','Release a little','How I feel now','The same'],['es','Deja ir','Usar sin micrófono','Liberar un poco','Cómo estoy ahora','Igual'],['fr','Laisse aller','Utiliser sans microphone','Libérer un peu','Comment je me sens','Pareil']])test('Zen translated, accessible touch alternative: '+language,async({page})=>{await fixture(page,'zen',language);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await page.getByRole('button',{name:without,exact:true}).click();await page.getByRole('button',{name:release,exact:true}).click();expect(await page.locator('body').innerText()).not.toMatch(/zen\./);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(language==='pt')await page.screenshot({path:'/tmp/confia-zen-partial.png',fullPage:true});await page.getByRole('button',{name:question,exact:true}).click();await page.getByRole('button',{name:same,exact:true}).click();});
test('microphone stream and AudioContext close on background; re-entry and rapid exit release late stream',async({page})=>{
 await page.addInitScript(()=>{const w=window as any;w.micStats={stopped:0,closed:0,active:false};w.pendingFrames=new Set();const raf=window.requestAnimationFrame.bind(window),cancel=window.cancelAnimationFrame.bind(window);window.requestAnimationFrame=callback=>{const id=raf(time=>{w.pendingFrames.delete(id);callback(time);});w.pendingFrames.add(id);return id;};window.cancelAnimationFrame=id=>{w.pendingFrames.delete(id);cancel(id);};let resolve:any;w.resolveMedia=()=>resolve({getTracks:()=>[track],getAudioTracks:()=>[track]});const track={stop:()=>w.micStats.stopped++,addEventListener:()=>{},removeEventListener:()=>{}};const node={connect:()=>{},disconnect:()=>{}};w.AudioContext=class{state='running';resume(){return Promise.resolve();}close(){w.micStats.closed++;this.state='closed';return Promise.resolve();}createMediaStreamSource(){w.micStats.active=true;return node;}createBiquadFilter(){return {...node,frequency:{value:0}};}createAnalyser(){return {...node,getFloatTimeDomainData:(data:Float32Array)=>data.fill(.01)};}};Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:()=>new Promise(yes=>resolve=yes)}});});
 await fixture(page,'zen');await page.getByRole('button',{name:'Permitir',exact:true}).click();await page.evaluate(()=>(window as any).resolveMedia());await expect.poll(()=>page.evaluate(()=>(window as any).micStats.active)).toBe(true);await page.evaluate(()=>(window as any).appListeners.forEach((cb:any)=>cb({isActive:false})));expect(await page.evaluate(()=>(window as any).micStats)).toEqual({stopped:1,closed:1,active:true});await page.getByRole('button',{name:'Usar o meu sopro',exact:true}).click();await page.getByRole('button',{name:'Sair deste momento',exact:true}).click();await page.evaluate(()=>(window as any).resolveMedia());await expect.poll(()=>page.evaluate(()=>(window as any).micStats.stopped)).toBe(2);expect(await page.evaluate(()=>(window as any).micStats.closed)).toBe(2);expect(await page.evaluate(()=>(window as any).pendingFrames.size)).toBe(0);
});
