import { useEffect,useRef,useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FOOD_CATALOG,FRUIT_ICONS,PERIODS,defaultUnit,isDrink,type FoodItem,type FoodUnit } from '../../data/habits/catalog';
import type { FoodType } from '../../data/habits/types';
import { buttonClass,inputClass,primaryClass } from './shared';
export default function FoodEditor({category,initial,onSave,onClose}:{category:FoodType;initial?:FoodItem;onSave:(item:FoodItem)=>boolean;onClose:()=>void}) {
 const {t}=useTranslation(),dialog=useRef<HTMLDialogElement>(null);
 const [value,setValue]=useState<FoodItem>(initial??{category,subtype:FOOD_CATALOG[category][0],quantity:1,unit:defaultUnit(category,FOOD_CATALOG[category][0]),deleted:false,...(isDrink(category)&&category!=='coffee'?{servingMl:250}:{})});
 const [error,setError]=useState(false);
 const patch=(next:Partial<FoodItem>)=>{setError(false);setValue(old=>({...old,...next}));};
 useEffect(()=>{const node=dialog.current;node?.showModal();return()=>node?.close();},[]);
 const timed=category==='coffee'||category==='energy'||category==='soda';
 return <dialog ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} className="food-sheet" aria-labelledby="food-editor-title">
 <form className="space-y-4 p-5" onSubmit={e=>{e.preventDefault();setError(!onSave(Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined&&v!=='')) as unknown as FoodItem));}}>
  <div className="flex items-center justify-between gap-3"><h3 id="food-editor-title" className="text-xl font-black">{t('habitHub.food.'+category)}</h3><button type="button" className={buttonClass} onClick={onClose}>{t('habitHub.detail.close')}</button></div>
  <fieldset><legend className="mb-2 text-sm font-bold">{t('habitHub.detail.type')}</legend><div className="grid grid-cols-2 gap-2">{FOOD_CATALOG[category].map(id=><button key={id} type="button" className={buttonClass+(value.subtype===id?' ring-2 ring-[#647852]':'')} aria-pressed={value.subtype===id} onClick={()=>patch({subtype:id,unit:defaultUnit(category,id)})}>{category==='fruit'&&FRUIT_ICONS[id]&&<span className="mb-1 block text-xl" aria-hidden="true">{FRUIT_ICONS[id]}</span>}{t('habitHub.catalog.'+category+'.'+id)}</button>)}</div></fieldset>
  <fieldset><legend className="mb-2 text-sm font-bold">{t('habitHub.detail.quantity')}</legend><div className="flex flex-wrap gap-2">{[0,1,2,3,4,5].map(n=><button type="button" className={buttonClass} key={n} aria-pressed={value.quantity===n} onClick={()=>patch({quantity:n})}>{n===5?'5+':n}</button>)}</div><div className="mt-2 flex items-center gap-2"><button type="button" aria-label={t('habitHub.detail.less')} className={buttonClass} disabled={value.quantity===0} onClick={()=>patch({quantity:Math.max(0,value.quantity-1)})}>−</button><label className="min-w-0 flex-1"><span className="sr-only">{t('habitHub.detail.exact')}</span><input type="number" inputMode="numeric" required min="0" max={value.unit==='ml'?10000:100} step="1" className={inputClass} value={value.quantity} onChange={e=>patch({quantity:Number(e.target.value)})}/></label><button type="button" className={buttonClass} aria-label={t('habitHub.detail.more')} onClick={()=>patch({quantity:Math.min(value.unit==='ml'?10000:100,value.quantity+1)})}>+</button></div></fieldset>
  {isDrink(category)&&category!=='coffee'?<div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">{t('habitHub.detail.unit')}<select aria-label={t('habitHub.detail.unit')} className={inputClass} value={value.unit} onChange={e=>patch({unit:e.target.value as FoodUnit})}>{['cup','can','bottle','ml'].map(k=><option key={k} value={k}>{t('habitHub.detail.units.'+k)}</option>)}</select></label>{value.unit!=='ml'&&<label className="text-sm font-bold">{t('habitHub.detail.volume')}<input type="number" required min="1" max="2000" step="1" className={inputClass} value={value.servingMl??250} onChange={e=>patch({servingMl:Number(e.target.value)})}/></label>}</div>:<p className="text-sm">{t('habitHub.detail.units.'+value.unit)}</p>}
  {timed&&<label className="block text-sm font-bold">{t('habitHub.detail.period')}<select className={inputClass} value={value.period??''} onChange={e=>patch({period:e.target.value as FoodItem['period']})}><option value="">{t('habitHub.optional')}</option>{PERIODS.map(k=><option key={k} value={k}>{t('habitHub.detail.periods.'+k)}</option>)}</select></label>}
  <details className="rounded-xl bg-white/60 p-3"><summary className="min-h-8 cursor-pointer text-sm font-bold">{t('habitHub.detail.optional')}</summary><div className="mt-3 space-y-3">
   {timed&&<label className="block text-sm">{t('habitHub.detail.time')}<input type="time" className={inputClass} value={value.time??''} onChange={e=>patch({time:e.target.value})}/></label>}
   {category==='coffee'&&<><label className="block text-sm">{t('habitHub.detail.size')}<select className={inputClass} value={value.size??''} onChange={e=>patch({size:e.target.value as FoodItem['size']})}><option value="">{t('habitHub.optional')}</option>{['small','medium','large'].map(k=><option key={k} value={k}>{t('habitHub.detail.sizes.'+k)}</option>)}</select></label><label className="block text-sm">{t('habitHub.detail.intensity')}<select className={inputClass} value={value.intensity??''} onChange={e=>patch({intensity:e.target.value as FoodItem['intensity']})}><option value="">{t('habitHub.optional')}</option>{['mild','medium','strong'].map(k=><option key={k} value={k}>{t('habitHub.detail.intensities.'+k)}</option>)}</select></label></>}
   {['soda','energy'].includes(category)&&<><p className="text-xs leading-5">{t('habitHub.detail.labelHelp')}</p>{(['caffeine','sugar'] as const).map(property=><label key={property} className="block text-sm">{t('habitHub.detail.'+property)}<select className={inputClass} value={value[property]??'unknown'} onChange={e=>patch({[property]:e.target.value})}>{['unknown','yes','no'].map(k=><option key={k} value={k}>{t('habitHub.detail.properties.'+k)}</option>)}</select></label>)}</>}
   <p className="text-xs leading-5">{t('habitHub.detail.noDose')}</p>
  </div></details>
  {error&&<p role="alert" className="rounded-xl bg-[#FFF2D9] p-3 text-sm">{t("habitHub.error")}</p>}
  <button type="submit" className={primaryClass+' w-full'}>{t('habitHub.detail.saveItem')}</button>
 </form></dialog>;
}
