import { hasOlderHabits,loadOlderHabits } from "../../data/habits/sync";
import { useEffect,useMemo,useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { HabitRecord } from '../../data/habits/types';
import type { PersonalEvent } from '../../data/personal/personalEvent';
import { eligiblePlans,suggestedPlanFromSignals,planDay,planAction,PLAN_TEMPLATES,type PlanRecord,type PlanId } from '../../data/habits/plans';
import { startWellbeingPlan,changeWellbeingPlan,recordPlanCheck,dismissPlanInvite } from '../../data/habits/planActions';
import { buttonClass,primaryClass,inputClass,type RunAction,formatDay } from './shared';
import { SourceNote } from './LifestyleReview';
export default function WellbeingPlans({records,today,run,events}:{records:HabitRecord[];today:string;run:RunAction;events:PersonalEvent[]}) {
 const {t,i18n}=useTranslation();const [historyLimit,setHistoryLimit]=useState(10),[loadingHistory,setLoadingHistory]=useState(false),[historyError,setHistoryError]=useState(false);
 const [selected,setSelected]=useState<PlanId|''>(''),[confirm,setConfirm]=useState(false);
 const plans=records.filter((r):r is PlanRecord=>r.kind==='wellbeingPlan').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
 const active=plans.find(r=>r.data.status==='active'||r.data.status==='paused');
 const eligible=useMemo(()=>eligiblePlans(records,today),[records,today]);
 const suggested=useMemo(()=>suggestedPlanFromSignals(events,eligible),[events,eligible]);
 const preference=records.find(r=>r.kind==='planPreference');
 const dismissed=preference?.kind==='planPreference'&&preference.data.dismissedUntil>today;
 const chosen=selected&&eligible.includes(selected)?selected:(suggested??eligible[0]);
 useEffect(()=>{if(active?.data.status==='active'&&today>active.data.endDate)run(()=>changeWellbeingPlan(active.id,'complete'),'');},[active?.id,active?.data.status,active?.data.endDate,today]);
 const renderResults=(plan:PlanRecord)=>{
  const {baseline,result,templateId}=plan.data;
  if(!result)return null;
  return <div className="mt-3 space-y-3 text-sm"><h4 className="font-bold">{t('habitHub.plans.results')}</h4>{baseline.days>=5&&result.days>=5?<><p>{t('habitHub.plans.comparison',{before:baseline.mean.toLocaleString(i18n.language,{maximumFractionDigits:1}),during:result.mean.toLocaleString(i18n.language,{maximumFractionDigits:1}),unit:t('habitHub.plans.metrics.'+templateId)})}</p><p className="text-xs">{t('habitHub.plans.sample',{before:baseline.days,during:result.days})}</p></>:<p>{t('habitHub.plans.notEnough')}</p>}{baseline.moodDays>=10&&result.moodDays>=10&&<p>{t('habitHub.plans.mood',{before:baseline.moodMean.toLocaleString(i18n.language,{maximumFractionDigits:1}),during:result.moodMean.toLocaleString(i18n.language,{maximumFractionDigits:1}),beforeDays:baseline.moodDays,duringDays:result.moodDays})}</p>}<p className="text-xs leading-5">{t('habitHub.plans.resultLimits')}</p></div>;
 };
 return <section className="space-y-4 rounded-[28px] border border-[#C9D8BD] bg-gradient-to-br from-[#F2F7E9] to-[#FFFDF7] p-5" aria-labelledby="wellbeing-plans-title"><h2 id="wellbeing-plans-title" className="text-xl font-black">{t('habitHub.plans.title')}</h2>
 {active?(()=>{const d=active.data,action=planAction(active,records,today),check=records.find(r=>r.kind==='planCheck'&&r.data.planId===active.id&&r.date===today);return <>
  <h3 className="font-bold">{t('habitHub.plans.names.'+d.templateId)}</h3><p className="text-sm">{t('habitHub.plans.day',{day:planDay(d,today)})} · {t('habitHub.plans.status.'+d.status)}</p><progress className="wellbeing-plan-progress h-2 w-full" aria-label={t('habitHub.plans.progress')} max="15" value={planDay(d,today)}/>
  {d.status==='active'&&<><p className="rounded-2xl bg-white/80 p-4 text-sm leading-6">{t(action.key)}</p>{action.easier&&<p className="text-xs">{t('habitHub.plans.adapted')}</p>}<div className="flex flex-wrap gap-2"><button type="button" className={primaryClass} aria-pressed={check?.kind==='planCheck'&&check.data.outcome==='done'} onClick={()=>run(()=>recordPlanCheck(active.id,true),t('habitHub.plans.noted'))}>{t('habitHub.plans.done')}</button><button type="button" className={buttonClass} aria-pressed={check?.kind==='planCheck'&&check.data.outcome==='notToday'} onClick={()=>run(()=>recordPlanCheck(active.id,false),t('habitHub.plans.kind'))}>{t('habitHub.plans.notToday')}</button></div>{check?.kind==='planCheck'&&check.data.outcome==='notToday'&&<p className="text-sm leading-6">{t('habitHub.plans.kind')}</p>}</>}
  <div className="flex flex-wrap gap-2"><button type="button" className={buttonClass} onClick={()=>run(()=>changeWellbeingPlan(active.id,d.status==='paused'?'resume':'pause'),'')}>{t('habitHub.plans.'+(d.status==='paused'?'resume':'pause'))}</button><button type="button" className={buttonClass} onClick={()=>run(()=>changeWellbeingPlan(active.id,'adjust'),'')}>{t('habitHub.plans.'+(d.gentle?'regular':'adjust'))}</button><button type="button" className={buttonClass} onClick={()=>setConfirm(true)}>{t('habitHub.plans.abandon')}</button></div>
  {confirm&&<div className="rounded-xl bg-white p-4"><p className="mb-3 text-sm">{t('habitHub.plans.abandonHelp')}</p><button type="button" className={buttonClass} onClick={()=>{if(run(()=>changeWellbeingPlan(active.id,'abandon'),t('habitHub.plans.kept')))setConfirm(false);}}>{t('habitHub.plans.confirmAbandon')}</button><button type="button" className={buttonClass+' ml-2'} onClick={()=>setConfirm(false)}>{t('habitHub.detail.close')}</button></div>}
  {PLAN_TEMPLATES.find(p=>p.id===d.templateId)?.source&&<SourceNote id={PLAN_TEMPLATES.find(p=>p.id===d.templateId)!.source!}/>}
  <details><summary className="min-h-11 cursor-pointer py-3 text-sm font-bold">{t('habitHub.clock.history')}</summary><ul className="space-y-2 text-sm">{records.filter((r):r is Extract<HabitRecord,{kind:'planCheck'}>=>r.kind==='planCheck'&&r.data.planId===active.id).sort((a,b)=>a.date.localeCompare(b.date)).map(r=><li key={r.id}>{formatDay(r.date,i18n.language)} · {t('habitHub.plans.day',{day:r.data.day})} · {t('habitHub.plans.'+(r.data.outcome==='done'?'done':'notToday'))}</li>)}</ul></details>
 </>;})():!dismissed&&eligible.length?<>
  <p className="text-sm leading-6">{t('habitHub.plans.invite')}</p><label className="block text-sm font-bold">{t('habitHub.plans.choose')}<select className={inputClass} value={chosen} onChange={e=>setSelected(e.target.value as PlanId)}>{eligible.map(id=><option key={id} value={id}>{t('habitHub.plans.names.'+id)}</option>)}</select></label><p className="text-sm leading-6">{t('habitHub.plans.consent')}</p><p className="rounded-xl bg-white p-3 text-sm">{t('habitHub.plans.steps.observe')}</p><div className="flex flex-wrap gap-2"><button type="button" className={primaryClass} onClick={()=>run(()=>startWellbeingPlan(chosen),t('habitHub.plans.started'))}>{t('habitHub.plans.try')}</button><button type="button" className={buttonClass} onClick={()=>run(dismissPlanInvite,'')}>{t('habitHub.plans.later')}</button></div>
 </>:<p className="text-sm leading-6">{t(dismissed?'habitHub.plans.dismissed':'habitHub.plans.empty')}</p>}
 {plans.filter(r=>['completed','abandoned'].includes(r.data.status)).slice(0,historyLimit).map(plan=><details key={plan.id} className="rounded-2xl bg-white/80 p-4"><summary className="min-h-11 cursor-pointer text-sm font-bold">{t('habitHub.plans.names.'+plan.data.templateId)} · {t('habitHub.plans.status.'+plan.data.status)} · {formatDay(plan.data.startDate,i18n.language)}</summary>{renderResults(plan)}<ul className="mt-3 space-y-1 text-xs">{records.filter((r):r is Extract<HabitRecord,{kind:'planCheck'}>=>r.kind==='planCheck'&&r.data.planId===plan.id).map(r=><li key={r.id}>{formatDay(r.date,i18n.language)} · {t('habitHub.plans.'+(r.data.outcome==='done'?'done':'notToday'))}</li>)}</ul></details>)}
 {plans.length>0&&(plans.length>historyLimit||hasOlderHabits())&&<button type="button" className={buttonClass} disabled={loadingHistory} onClick={async()=>{setLoadingHistory(true);setHistoryError(false);try{if(hasOlderHabits())await loadOlderHabits();setHistoryLimit(n=>n+10);}catch{setHistoryError(true);}finally{setLoadingHistory(false);}}}>{t('habitHub.detail.loadMore')}</button>}
 {historyError&&<p role="alert" className="text-sm">{t('habitHub.error')}</p>}
 <p className="text-xs leading-5 text-[#6F5D51]">{t('habitHub.plans.safety')}</p></section>;
}
