import { useEffect,useMemo,useState } from "react"; import { HeartHandshake,MessagesSquare,Sparkles,UsersRound,Vote } from "lucide-react"; import { useTranslation } from "react-i18next"; import type { SharePost } from "../types"; import { auth } from "../firebaseAuth"; import { createCommunityPoll,subscribeCommunityPolls,voteCommunityPoll,type CommunityPoll } from "../data/community/communityPremiumService";
type Mode="other_side"|"match"|"circles"|"poll"|"give_back"|null;
type Props={posts:SharePost[];onConnect:(post:SharePost)=>Promise<void>|void;onCreate:(feeling:string,topic:string,message:string,options?:{experienceTag?:string;supportMode?:"share"|"other_side"|"seeking_match"|"give_back";circleExpiresAt?:number})=>Promise<void>|void;onOpenChat:(post:SharePost)=>void};
const experiences=["rumination","sleep","work","loneliness","panic","body_sensations","family","relationships"];
export default function CommunityPremiumHub({posts,onConnect,onCreate,onOpenChat}:Props){const{t}=useTranslation();const[mode,setMode]=useState<Mode>(null);const[experience,setExperience]=useState("rumination");const[text,setText]=useState("");const[polls,setPolls]=useState<CommunityPoll[]>([]);const[pollQuestion,setPollQuestion]=useState("");
 useEffect(()=>subscribeCommunityPolls(setPolls),[]);const mine=auth.currentUser?.uid;
 const matches=useMemo(()=>posts.filter(p=>p.authorId!==mine&&(p.experienceTag===experience||p.topic===experience)).slice(0,5),[posts,experience,mine]);
 const otherSide=posts.filter(p=>p.supportMode==="other_side"||p.supportMode==="give_back").slice(0,5);const circles=posts.filter(p=>p.circleExpiresAt&&p.circleExpiresAt>Date.now()).slice(0,8);
 const submit=async(kind:"other_side"|"seeking_match"|"give_back",circle=false)=>{if(!text.trim())return;await onCreate("Calmo",experience==="work"?"trabalho-estudos":experience==="sleep"?"sono":experience==="family"?"familia":experience==="relationships"?"relacoes":"ansiedade",text.trim(),{experienceTag:experience,supportMode:kind,circleExpiresAt:circle?Date.now()+7*86400000:undefined});setText("");setMode(null)};
 const cards=[{id:"other_side" as const,icon:<Sparkles size={17}/>,title:t("communityPremium.otherSide.title"),sub:t("communityPremium.otherSide.sub")},{id:"match" as const,icon:<HeartHandshake size={17}/>,title:t("communityPremium.match.title"),sub:t("communityPremium.match.sub")},{id:"circles" as const,icon:<UsersRound size={17}/>,title:t("communityPremium.circles.title"),sub:t("communityPremium.circles.sub")},{id:"poll" as const,icon:<Vote size={17}/>,title:t("communityPremium.poll.title"),sub:t("communityPremium.poll.sub")},{id:"give_back" as const,icon:<MessagesSquare size={17}/>,title:t("communityPremium.giveBack.title"),sub:t("communityPremium.giveBack.sub")}];
 return <section className="rounded-[30px] border border-[#E8DDD7] bg-gradient-to-b from-white to-[#FFF9F5] p-4 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#B85F48]">CONFIA · {t("communityPremium.eyebrow")}</p><h3 className="mt-1 text-lg font-black text-[#2F2926]">{t("communityPremium.title")}</h3><p className="mt-1 text-[11px] leading-5 text-[#806D65]">{t("communityPremium.subtitle")}</p><div className="mt-4 grid grid-cols-2 gap-2">{cards.map(c=><button key={c.id} type="button" onClick={()=>setMode(mode===c.id?null:c.id)} className="rounded-2xl border border-[#EADBD3] bg-white p-3 text-left"><span className="text-[#B85F48]">{c.icon}</span><b className="mt-2 block text-[11px] text-[#3F2C27]">{c.title}</b><span className="mt-1 block text-[9px] leading-4 text-[#806D65]">{c.sub}</span></button>)}</div>
 {mode&&<div className="mt-4 rounded-2xl bg-[#F8F1ED] p-4">{mode!=="poll"&&<div className="flex gap-2 overflow-x-auto pb-2">{experiences.map(x=><button key={x} onClick={()=>setExperience(x)} className={(experience===x?"bg-[#3F2C27] text-white":"bg-white text-[#795B50]")+" shrink-0 rounded-full px-3 py-2 text-[9px] font-black"}>{t("communityPremium.experiences."+x)}</button>)}</div>}
 {mode==="match"&&<div className="mt-2 space-y-2"><p className="text-[10px] text-[#806D65]">{t("communityPremium.match.disclaimer")}</p>{matches.length?matches.map(p=><button key={p.id} onClick={()=>onConnect(p)} className="w-full rounded-xl bg-white p-3 text-left"><b className="text-[10px] text-[#934A38]">{t("communityPremium.match.compatible")}</b><p className="mt-1 line-clamp-2 text-[11px] text-[#5E4A43]">{p.message}</p></button>):<p className="rounded-xl bg-white p-3 text-[10px] text-[#806D65]">{t("communityPremium.match.none")}</p>}</div>}
 {mode==="other_side"&&<div className="mt-2 space-y-2">{otherSide.filter(p=>!p.experienceTag||p.experienceTag===experience).map(p=><div key={p.id} className="rounded-xl bg-white p-3"><b className="text-[9px] text-[#587563]">{t("communityPremium.otherSide.fromOtherSide")}</b><p className="mt-1 text-[11px] leading-5 text-[#5E4A43]">{p.message}</p></div>)}<textarea value={text} onChange={e=>setText(e.target.value.slice(0,220))} placeholder={t("communityPremium.otherSide.placeholder")} className="w-full rounded-xl border border-[#E8DDD7] p-3 text-xs"/><button onClick={()=>submit("other_side")} className="min-h-10 w-full rounded-xl bg-[#587563] text-xs font-black text-white">{t("communityPremium.publish")}</button></div>}
 {mode==="give_back"&&<div className="mt-2"><p className="mb-2 text-[10px] leading-4 text-[#806D65]">{t("communityPremium.giveBack.prompt")}</p><textarea value={text} onChange={e=>setText(e.target.value.slice(0,220))} placeholder={t("communityPremium.giveBack.placeholder")} className="w-full rounded-xl border border-[#E8DDD7] p-3 text-xs"/><button onClick={()=>submit("give_back")} className="mt-2 min-h-10 w-full rounded-xl bg-[#587563] text-xs font-black text-white">{t("communityPremium.giveBack.action")}</button></div>}
 {mode==="circles"&&<div className="mt-2 space-y-2"><p className="text-[10px] text-[#806D65]">{t("communityPremium.circles.explain")}</p>{circles.filter(p=>p.experienceTag===experience).map(p=><button key={p.id} onClick={()=>onOpenChat(p)} className="w-full rounded-xl bg-white p-3 text-left text-[11px] text-[#5E4A43]">{p.message}</button>)}<textarea value={text} onChange={e=>setText(e.target.value.slice(0,220))} placeholder={t("communityPremium.circles.placeholder")} className="w-full rounded-xl border border-[#E8DDD7] p-3 text-xs"/><button onClick={()=>submit("seeking_match",true)} className="min-h-10 w-full rounded-xl bg-[#934A38] text-xs font-black text-white">{t("communityPremium.circles.create")}</button></div>}
 {mode==="poll"&&<div className="mt-2 space-y-3"><p className="text-[10px] leading-4 text-[#806D65]">{t("communityPremium.poll.disclaimer")}</p><input value={pollQuestion} onChange={e=>setPollQuestion(e.target.value.slice(0,180))} placeholder={t("communityPremium.poll.placeholder")} className="w-full rounded-xl border border-[#E8DDD7] p-3 text-xs"/><button onClick={async()=>{if(pollQuestion.trim()){await createCommunityPoll(pollQuestion,"experiencia");setPollQuestion("")}}} className="min-h-10 w-full rounded-xl bg-[#934A38] text-xs font-black text-white">{t("communityPremium.poll.create")}</button>{polls.map(p=><div key={p.id} className="rounded-xl bg-white p-3"><b className="text-[11px] text-[#3F2C27]">{p.question}</b><div className="mt-2 grid grid-cols-2 gap-2">{p.options.map(o=><button key={o.id} disabled={o.voterIds?.includes(mine||"")} onClick={()=>voteCommunityPoll(p,o.id)} className="rounded-xl bg-[#FFF7F2] px-2 py-2 text-[9px] font-bold text-[#795B50] disabled:opacity-60">{t("communityPremium.poll.options."+o.label)} · {o.count}</button>)}</div></div>)}</div>}
 </div>}</section>}
