import { memo, useMemo, useState } from "react";
import { ArrowLeft, Brain, ChevronRight, LockKeyhole, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { useTranslation } from "react-i18next";
import { readPersonalEvents } from "../data/personal/personalEventStorage";
import { askMyHistory, buildPersonalIntelligenceSnapshot, type HistoryQuestion } from "../data/personal/premiumIntelligence";

type Props = { onBack: () => void };
const QUESTIONS: Array<{ id: HistoryQuestion; icon: string }> = [
  { id: "what_helps", icon: "🌱" }, { id: "am_i_changing", icon: "📈" },
  { id: "have_i_been_here", icon: "🔎" }, { id: "when_harder", icon: "🧭" },
];
export const PremiumIntelligence = memo(function PremiumIntelligence({ onBack }: Props) {
  const { t } = useTranslation();
  const [question, setQuestion] = useState<HistoryQuestion | null>(null);
  const events = useMemo(() => readPersonalEvents(), []);
  const snapshot = useMemo(() => buildPersonalIntelligenceSnapshot(events, new Date()), [events]);
  const answer = useMemo(() => question ? askMyHistory(events, question, new Date()) : null, [events, question]);
  const scaleLabels: Record<string, string> = {"24h":t("premiumIntelligence.scales.day"),"7d":t("premiumIntelligence.scales.week"),"30d":t("premiumIntelligence.scales.month"),"90d":t("premiumIntelligence.scales.quarter"),history:t("premiumIntelligence.scales.history")};
  const interventions = snapshot.interventions.slice(0,3);
  return <div className="space-y-5 pb-4">
    <div className="flex items-center gap-3"><button type="button" onClick={onBack} aria-label={t("back")} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-[#E8DDD7]/80 bg-white text-[#934A38] shadow-sm transition-transform active:scale-95"><ArrowLeft size={18}/></button><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#934A38]">{t("premiumIntelligence.eyebrow")}</p><h2 className="text-xl font-black tracking-tight text-[#2F2926]">{t("premiumIntelligence.title")}</h2></div><div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-[#D7B36A]/35 bg-[#FFF7E7] text-[#9B6B20]"><Sparkles size={18}/></div></div>
    <section className="relative overflow-hidden rounded-[30px] border border-[#D7B36A]/35 bg-gradient-to-br from-[#FFFDF8] via-white to-[#FFF5E6] p-5 shadow-[0_16px_36px_rgba(91,65,36,0.08)]"><div className="relative"><div className="flex items-center gap-2 text-[#9B6B20]"><Brain size={18}/><span className="text-[10px] font-black uppercase tracking-[0.16em]">{t("premiumIntelligence.badge")}</span></div><h3 className="mt-3 text-lg font-black text-[#2F2926]">{t("premiumIntelligence.heroTitle")}</h3><p className="mt-2 text-xs font-semibold leading-relaxed text-[#6D5A50]">{t("premiumIntelligence.heroText")}</p><div className="mt-4 flex items-center gap-2 rounded-2xl border border-[#E8DDD7] bg-white/80 px-3 py-2.5"><span className="text-lg">🧠</span><p className="text-[10px] font-bold leading-relaxed text-[#5D4C45]">{t("premiumIntelligence.dataNote",{count:events.length})}</p></div></div></section>
    <section className="rounded-[28px] border border-[#E8DDD7] bg-white p-4 shadow-[0_10px_28px_rgba(92,64,52,0.045)]"><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="text-sm font-black text-[#2F2926]">{t("premiumIntelligence.scales.title")}</h3><p className="mt-0.5 text-[10px] font-semibold text-[var(--cf-muted)]">{t("premiumIntelligence.scales.subtitle")}</p></div><span className="rounded-full bg-[#F7F1EC] px-2.5 py-1 text-[9px] font-black text-[#806D65]">{events.length} {t("premiumIntelligence.observations")}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{snapshot.timeScales.map(scale=><div key={scale.label} className="rounded-2xl border border-[#EEE5DF] bg-[#FFFCFA] p-3"><p className="text-[9px] font-black uppercase tracking-wide text-[#8D756B]">{scaleLabels[scale.label]??scale.label}</p><p className="mt-1 text-lg font-black text-[#2F2926]">{scale.observationCount}</p><p className="text-[9px] font-semibold text-[#9A8880]">{scale.activeDays} {t("premiumIntelligence.activeDays")}</p></div>)}</div></section>
    <section className="rounded-[28px] border border-[#E8DDD7] bg-white p-4 shadow-[0_10px_28px_rgba(92,64,52,0.045)]"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[#F3E3DC] text-[#934A38]"><Sparkles size={18}/></div><div><h3 className="text-sm font-black text-[#2F2926]">{t("premiumIntelligence.learning.title")}</h3><p className="mt-1 text-[10px] font-semibold leading-relaxed text-[var(--cf-muted)]">{t("premiumIntelligence.learning.subtitle")}</p></div></div>{snapshot.strongestLearning?<div className="mt-4 rounded-2xl border border-[#E8DDD7] bg-[#FFFCFA] p-4"><p className="text-xs font-bold leading-relaxed text-[#4E4039]">{snapshot.strongestLearning.evidenceCount} {t("premiumIntelligence.evidence")}. </p><div className="mt-3 flex items-center gap-2 text-[9px] font-black text-[#806D65]"><span className="rounded-full bg-[#F3E3DC] px-2 py-1">{t("premiumIntelligence.confidence."+snapshot.strongestLearning.confidence)}</span><span>{snapshot.strongestLearning.evidenceCount} {t("premiumIntelligence.evidence")}</span></div></div>:<div className="mt-4 rounded-2xl border border-dashed border-[#DCCFC8] bg-[#FFFCFA] p-4 text-xs font-semibold leading-relaxed text-[#76645C]">{t("premiumIntelligence.learning.insufficient")}</div>}</section>
    {interventions.length>0&&<section className="rounded-[28px] border border-[#E8DDD7] bg-white p-4 shadow-[0_10px_28px_rgba(92,64,52,0.045)]"><div className="mb-3"><h3 className="text-sm font-black text-[#2F2926]">{t("premiumIntelligence.interventions.title")}</h3><p className="mt-1 text-[10px] font-semibold text-[var(--cf-muted)]">{t("premiumIntelligence.interventions.subtitle")}</p></div><div className="space-y-2">{interventions.map(item=><div key={item.id} className="flex items-center gap-3 rounded-2xl border border-[#EEE5DF] bg-[#FFFCFA] p-3">{item.averageReduction>0?<TrendingDown size={17} className="text-[#4F7A58]"/>:<TrendingUp size={17} className="text-[#A65A4D]"/>}<div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#4E4039]">{item.interventionId}</p><p className="text-[9px] font-semibold text-[#8B7870]">{item.improved}/{item.attempts} {t("premiumIntelligence.interventions.improved")}</p></div><span className="text-[9px] font-black text-[#806D65]">{t("premiumIntelligence.confidence."+item.confidence)}</span></div>)}</div></section>}
    <section className="rounded-[28px] border border-[#D7B36A]/30 bg-gradient-to-br from-white to-[#FFF9EF] p-4 shadow-[0_12px_30px_rgba(92,64,52,0.05)]"><div className="mb-3"><h3 className="text-sm font-black text-[#2F2926]">{t("premiumIntelligence.ask.title")}</h3><p className="mt-1 text-[10px] font-semibold leading-relaxed text-[var(--cf-muted)]">{t("premiumIntelligence.ask.subtitle")}</p></div><div className="grid grid-cols-1 gap-2">{QUESTIONS.map(item=><button key={item.id} type="button" onClick={()=>setQuestion(item.id)} className="flex min-h-11 items-center gap-3 rounded-2xl border border-[#E8DDD7] bg-white px-3.5 py-3 text-left transition-all active:scale-[0.99] hover:border-[#D7B36A]/55"><span className="text-base">{item.icon}</span><span className="flex-1 text-[11px] font-black text-[#4E4039]">{t("premiumIntelligence.questions."+item.id)}</span><ChevronRight size={15} className="text-[#A48F85]"/></button>)}</div>{answer&&<div className="mt-3 rounded-2xl border border-[#E4D6BF] bg-white p-4"><p className="text-xs font-black leading-relaxed text-[#4E4039]">{answer.answer}</p><p className="mt-2 text-[9px] font-semibold leading-relaxed text-[#8A776E]">{answer.why}</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-[#F7F1EC] px-2.5 py-1 text-[9px] font-black text-[#806D65]">{t("premiumIntelligence.confidence."+answer.confidence)}</span>{answer.insufficient&&<span className="rounded-full bg-[#FFF4E8] px-2.5 py-1 text-[9px] font-black text-[#8A6400]">{t("premiumIntelligence.insufficient")}</span>}</div></div>}</section>
    <div className="flex items-start gap-2 rounded-2xl border border-[#E8DDD7] bg-[#FBF8F6] px-3.5 py-3"><LockKeyhole size={15} className="mt-0.5 shrink-0 text-[#8B7770]"/><p className="text-[9px] font-semibold leading-relaxed text-[#806D65]">{t("premiumIntelligence.guardrail")}</p></div>
  </div>;
});
