export type ConstellationReflectionLanguage = "pt" | "en" | "es" | "fr";

/**
 * Reflexões CONFIA associadas ao resultado visual.
 * Não representam significado astronómico, diagnóstico, previsão ou astrologia.
 */
export const CONSTELLATION_REFLECTIONS: Record<
  string,
  Record<ConstellationReflectionLanguage, string>
> = {
  "andromeda": {
    pt: "Hoje, Andromeda pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Andromeda can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Andromeda puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Andromeda peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "antlia": {
    pt: "Hoje, Antlia pode servir apenas como um ponto de contemplação. Parar por um momento também faz parte do caminho; nem todo o progresso precisa de ser movimento.",
    en: "Today, Antlia can simply serve as a point of contemplation. Stopping for a moment is also part of the path; not all progress has to look like movement.",
    es: "Hoy, Antlia puede servir simplemente como un punto de contemplación. Detenerte un momento también forma parte del camino; no todo progreso tiene que parecer movimiento.",
    fr: "Aujourd’hui, Antlia peut simplement servir de point de contemplation. S’arrêter un instant fait aussi partie du chemin ; tout progrès n’a pas besoin de prendre la forme d’un mouvement.",
  },
  "apus": {
    pt: "Hoje, Apus pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Apus can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Apus puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Apus peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "aquarius": {
    pt: "Hoje, Aquarius pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Aquarius can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Aquarius puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Aquarius peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "aquila": {
    pt: "Hoje, Aquila pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Aquila can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Aquila puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Aquila peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "ara": {
    pt: "Hoje, Ara pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Ara can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Ara puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Ara peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "aries": {
    pt: "Hoje, Aries pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Aries can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Aries puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Aries peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "auriga": {
    pt: "Hoje, Auriga pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Auriga can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Auriga puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Auriga peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "bootes": {
    pt: "Hoje, Boötes pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Boötes can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Boötes puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Boötes peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "caelum": {
    pt: "Hoje, Caelum pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Caelum can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Caelum puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Caelum peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "camelopardalis": {
    pt: "Hoje, Camelopardalis pode servir apenas como um ponto de contemplação. Nem tudo precisa de uma resposta imediata; algumas formas tornam-se mais claras quando lhes damos tempo.",
    en: "Today, Camelopardalis can simply serve as a point of contemplation. Not everything needs an immediate answer; some shapes become clearer when we give them time.",
    es: "Hoy, Camelopardalis puede servir simplemente como un punto de contemplación. No todo necesita una respuesta inmediata; algunas formas se vuelven más claras cuando les damos tiempo.",
    fr: "Aujourd’hui, Camelopardalis peut simplement servir de point de contemplation. Tout n’exige pas une réponse immédiate ; certaines formes deviennent plus claires lorsqu’on leur laisse du temps.",
  },
  "cancer": {
    pt: "Hoje, Cancer pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Cancer can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Cancer puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Cancer peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "canes_venatici": {
    pt: "Hoje, Canes Venatici pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Canes Venatici can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Canes Venatici puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Canes Venatici peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "canis_major": {
    pt: "Hoje, Canis Major pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Canis Major can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Canis Major puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Canis Major peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "canis_minor": {
    pt: "Hoje, Canis Minor pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Canis Minor can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Canis Minor puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Canis Minor peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "capricornus": {
    pt: "Hoje, Capricornus pode servir apenas como um ponto de contemplação. Nem tudo precisa de uma resposta imediata; algumas formas tornam-se mais claras quando lhes damos tempo.",
    en: "Today, Capricornus can simply serve as a point of contemplation. Not everything needs an immediate answer; some shapes become clearer when we give them time.",
    es: "Hoy, Capricornus puede servir simplemente como un punto de contemplación. No todo necesita una respuesta inmediata; algunas formas se vuelven más claras cuando les damos tiempo.",
    fr: "Aujourd’hui, Capricornus peut simplement servir de point de contemplation. Tout n’exige pas une réponse immédiate ; certaines formes deviennent plus claires lorsqu’on leur laisse du temps.",
  },
  "carina": {
    pt: "Hoje, Carina pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Carina can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Carina puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Carina peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "cassiopeia": {
    pt: "Hoje, Cassiopeia pode servir apenas como um ponto de contemplação. Mudar um pouco o ponto de vista pode revelar uma forma que antes passava despercebida.",
    en: "Today, Cassiopeia can simply serve as a point of contemplation. A small change of perspective can reveal a shape that previously went unnoticed.",
    es: "Hoy, Cassiopeia puede servir simplemente como un punto de contemplación. Cambiar un poco el punto de vista puede revelar una forma que antes pasaba desapercibida.",
    fr: "Aujourd’hui, Cassiopeia peut simplement servir de point de contemplation. Changer légèrement de point de vue peut révéler une forme qui passait auparavant inaperçue.",
  },
  "centaurus": {
    pt: "Hoje, Centaurus pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Centaurus can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Centaurus puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Centaurus peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "cepheus": {
    pt: "Hoje, Cepheus pode servir apenas como um ponto de contemplação. Mudar um pouco o ponto de vista pode revelar uma forma que antes passava despercebida.",
    en: "Today, Cepheus can simply serve as a point of contemplation. A small change of perspective can reveal a shape that previously went unnoticed.",
    es: "Hoy, Cepheus puede servir simplemente como un punto de contemplación. Cambiar un poco el punto de vista puede revelar una forma que antes pasaba desapercibida.",
    fr: "Aujourd’hui, Cepheus peut simplement servir de point de contemplation. Changer légèrement de point de vue peut révéler une forme qui passait auparavant inaperçue.",
  },
  "cetus": {
    pt: "Hoje, Cetus pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Cetus can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Cetus puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Cetus peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "chamaeleon": {
    pt: "Hoje, Chamaeleon pode servir apenas como um ponto de contemplação. Nem tudo precisa de uma resposta imediata; algumas formas tornam-se mais claras quando lhes damos tempo.",
    en: "Today, Chamaeleon can simply serve as a point of contemplation. Not everything needs an immediate answer; some shapes become clearer when we give them time.",
    es: "Hoy, Chamaeleon puede servir simplemente como un punto de contemplación. No todo necesita una respuesta inmediata; algunas formas se vuelven más claras cuando les damos tiempo.",
    fr: "Aujourd’hui, Chamaeleon peut simplement servir de point de contemplation. Tout n’exige pas une réponse immédiate ; certaines formes deviennent plus claires lorsqu’on leur laisse du temps.",
  },
  "circinus": {
    pt: "Hoje, Circinus pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Circinus can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Circinus puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Circinus peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "columba": {
    pt: "Hoje, Columba pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Columba can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Columba puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Columba peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "coma_berenices": {
    pt: "Hoje, Coma Berenices pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Coma Berenices can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Coma Berenices puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Coma Berenices peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "corona_australis": {
    pt: "Hoje, Corona Australis pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Corona Australis can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Corona Australis puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Corona Australis peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "corona_borealis": {
    pt: "Hoje, Corona Borealis pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Corona Borealis can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Corona Borealis puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Corona Borealis peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "corvus": {
    pt: "Hoje, Corvus pode servir apenas como um ponto de contemplação. Mudar um pouco o ponto de vista pode revelar uma forma que antes passava despercebida.",
    en: "Today, Corvus can simply serve as a point of contemplation. A small change of perspective can reveal a shape that previously went unnoticed.",
    es: "Hoy, Corvus puede servir simplemente como un punto de contemplación. Cambiar un poco el punto de vista puede revelar una forma que antes pasaba desapercibida.",
    fr: "Aujourd’hui, Corvus peut simplement servir de point de contemplation. Changer légèrement de point de vue peut révéler une forme qui passait auparavant inaperçue.",
  },
  "crater": {
    pt: "Hoje, Crater pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Crater can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Crater puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Crater peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "crux": {
    pt: "Hoje, Crux pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Crux can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Crux puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Crux peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "cygnus": {
    pt: "Hoje, Cygnus pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Cygnus can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Cygnus puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Cygnus peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "delphinus": {
    pt: "Hoje, Delphinus pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Delphinus can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Delphinus puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Delphinus peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "dorado": {
    pt: "Hoje, Dorado pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Dorado can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Dorado puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Dorado peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "draco": {
    pt: "Hoje, Draco pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Draco can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Draco puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Draco peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "equuleus": {
    pt: "Hoje, Equuleus pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Equuleus can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Equuleus puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Equuleus peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "eridanus": {
    pt: "Hoje, Eridanus pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Eridanus can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Eridanus puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Eridanus peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "fornax": {
    pt: "Hoje, Fornax pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Fornax can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Fornax puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Fornax peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "gemini": {
    pt: "Hoje, Gemini pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Gemini can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Gemini puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Gemini peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "grus": {
    pt: "Hoje, Grus pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Grus can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Grus puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Grus peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "hercules": {
    pt: "Hoje, Hercules pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Hercules can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Hercules puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Hercules peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "horologium": {
    pt: "Hoje, Horologium pode servir apenas como um ponto de contemplação. Nem tudo precisa de uma resposta imediata; algumas formas tornam-se mais claras quando lhes damos tempo.",
    en: "Today, Horologium can simply serve as a point of contemplation. Not everything needs an immediate answer; some shapes become clearer when we give them time.",
    es: "Hoy, Horologium puede servir simplemente como un punto de contemplación. No todo necesita una respuesta inmediata; algunas formas se vuelven más claras cuando les damos tiempo.",
    fr: "Aujourd’hui, Horologium peut simplement servir de point de contemplation. Tout n’exige pas une réponse immédiate ; certaines formes deviennent plus claires lorsqu’on leur laisse du temps.",
  },
  "hydra": {
    pt: "Hoje, Hydra pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Hydra can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Hydra puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Hydra peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "hydrus": {
    pt: "Hoje, Hydrus pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Hydrus can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Hydrus puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Hydrus peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "indus": {
    pt: "Hoje, Indus pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Indus can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Indus puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Indus peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "lacerta": {
    pt: "Hoje, Lacerta pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Lacerta can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Lacerta puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Lacerta peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "leo": {
    pt: "Hoje, Leo pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Leo can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Leo puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Leo peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "leo_minor": {
    pt: "Hoje, Leo Minor pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Leo Minor can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Leo Minor puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Leo Minor peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "lepus": {
    pt: "Hoje, Lepus pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Lepus can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Lepus puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Lepus peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "libra": {
    pt: "Hoje, Libra pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Libra can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Libra puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Libra peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "lupus": {
    pt: "Hoje, Lupus pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Lupus can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Lupus puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Lupus peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "lynx": {
    pt: "Hoje, Lynx pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Lynx can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Lynx puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Lynx peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "lyra": {
    pt: "Hoje, Lyra pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Lyra can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Lyra puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Lyra peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "mensa": {
    pt: "Hoje, Mensa pode servir apenas como um ponto de contemplação. Parar por um momento também faz parte do caminho; nem todo o progresso precisa de ser movimento.",
    en: "Today, Mensa can simply serve as a point of contemplation. Stopping for a moment is also part of the path; not all progress has to look like movement.",
    es: "Hoy, Mensa puede servir simplemente como un punto de contemplación. Detenerte un momento también forma parte del camino; no todo progreso tiene que parecer movimiento.",
    fr: "Aujourd’hui, Mensa peut simplement servir de point de contemplation. S’arrêter un instant fait aussi partie du chemin ; tout progrès n’a pas besoin de prendre la forme d’un mouvement.",
  },
  "microscopium": {
    pt: "Hoje, Microscopium pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Microscopium can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Microscopium puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Microscopium peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "monoceros": {
    pt: "Hoje, Monoceros pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Monoceros can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Monoceros puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Monoceros peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "musca": {
    pt: "Hoje, Musca pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Musca can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Musca puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Musca peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "norma": {
    pt: "Hoje, Norma pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Norma can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Norma puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Norma peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "octans": {
    pt: "Hoje, Octans pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Octans can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Octans puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Octans peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "ophiuchus": {
    pt: "Hoje, Ophiuchus pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Ophiuchus can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Ophiuchus puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Ophiuchus peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "orion": {
    pt: "Hoje, Orion pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Orion can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Orion puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Orion peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "pavo": {
    pt: "Hoje, Pavo pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Pavo can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Pavo puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Pavo peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "pegasus": {
    pt: "Hoje, Pegasus pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Pegasus can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Pegasus puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Pegasus peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "perseus": {
    pt: "Hoje, Perseus pode servir apenas como um ponto de contemplação. A coragem de hoje pode ser apenas continuar, sem precisares de conhecer já todo o caminho.",
    en: "Today, Perseus can simply serve as a point of contemplation. Today's courage may simply be continuing without needing to know the whole path yet.",
    es: "Hoy, Perseus puede servir simplemente como un punto de contemplación. El valor de hoy puede ser simplemente continuar sin necesitar conocer todavía todo el camino.",
    fr: "Aujourd’hui, Perseus peut simplement servir de point de contemplation. Le courage d’aujourd’hui peut simplement consister à continuer sans devoir déjà connaître tout le chemin.",
  },
  "phoenix": {
    pt: "Hoje, Phoenix pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Phoenix can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Phoenix puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Phoenix peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "pictor": {
    pt: "Hoje, Pictor pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Pictor can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Pictor puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Pictor peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "pisces": {
    pt: "Hoje, Pisces pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Pisces can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Pisces puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Pisces peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "piscis_austrinus": {
    pt: "Hoje, Piscis Austrinus pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Piscis Austrinus can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Piscis Austrinus puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Piscis Austrinus peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "puppis": {
    pt: "Hoje, Puppis pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Puppis can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Puppis puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Puppis peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "pyxis": {
    pt: "Hoje, Pyxis pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Pyxis can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Pyxis puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Pyxis peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "reticulum": {
    pt: "Hoje, Reticulum pode servir apenas como um ponto de contemplação. Repara nas ligações que te sustentam, incluindo aquelas que quase passam despercebidas.",
    en: "Today, Reticulum can simply serve as a point of contemplation. Notice the connections that support you, including the ones that are easy to overlook.",
    es: "Hoy, Reticulum puede servir simplemente como un punto de contemplación. Observa las conexiones que te sostienen, incluidas aquellas que casi pasan desapercibidas.",
    fr: "Aujourd’hui, Reticulum peut simplement servir de point de contemplation. Remarque les liens qui te soutiennent, y compris ceux qui passent presque inaperçus.",
  },
  "sagitta": {
    pt: "Hoje, Sagitta pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Sagitta can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Sagitta puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Sagitta peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "sagittarius": {
    pt: "Hoje, Sagittarius pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Sagittarius can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Sagittarius puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Sagittarius peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "scorpius": {
    pt: "Hoje, Scorpius pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Scorpius can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Scorpius puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Scorpius peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "sculptor": {
    pt: "Hoje, Sculptor pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Sculptor can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Sculptor puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Sculptor peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "scutum": {
    pt: "Hoje, Scutum pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Scutum can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Scutum puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Scutum peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "serpens": {
    pt: "Hoje, Serpens pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Serpens can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Serpens puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Serpens peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "sextans": {
    pt: "Hoje, Sextans pode servir apenas como um ponto de contemplação. Mudar um pouco o ponto de vista pode revelar uma forma que antes passava despercebida.",
    en: "Today, Sextans can simply serve as a point of contemplation. A small change of perspective can reveal a shape that previously went unnoticed.",
    es: "Hoy, Sextans puede servir simplemente como un punto de contemplación. Cambiar un poco el punto de vista puede revelar una forma que antes pasaba desapercibida.",
    fr: "Aujourd’hui, Sextans peut simplement servir de point de contemplation. Changer légèrement de point de vue peut révéler une forme qui passait auparavant inaperçue.",
  },
  "taurus": {
    pt: "Hoje, Taurus pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Taurus can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Taurus puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Taurus peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "telescopium": {
    pt: "Hoje, Telescopium pode servir apenas como um ponto de contemplação. Mudar um pouco o ponto de vista pode revelar uma forma que antes passava despercebida.",
    en: "Today, Telescopium can simply serve as a point of contemplation. A small change of perspective can reveal a shape that previously went unnoticed.",
    es: "Hoy, Telescopium puede servir simplemente como un punto de contemplación. Cambiar un poco el punto de vista puede revelar una forma que antes pasaba desapercibida.",
    fr: "Aujourd’hui, Telescopium peut simplement servir de point de contemplation. Changer légèrement de point de vue peut révéler une forme qui passait auparavant inaperçue.",
  },
  "triangulum": {
    pt: "Hoje, Triangulum pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Triangulum can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Triangulum puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Triangulum peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "triangulum_australe": {
    pt: "Hoje, Triangulum Australe pode servir apenas como um ponto de contemplação. Entre o impulso e a pausa, pode existir um ponto onde consigas escutar-te com mais clareza.",
    en: "Today, Triangulum Australe can simply serve as a point of contemplation. Between momentum and pause, there may be a point where you can hear yourself more clearly.",
    es: "Hoy, Triangulum Australe puede servir simplemente como un punto de contemplación. Entre el impulso y la pausa puede existir un punto en el que puedas escucharte con más claridad.",
    fr: "Aujourd’hui, Triangulum Australe peut simplement servir de point de contemplation. Entre l’élan et la pause, il peut exister un point où tu peux t’écouter avec plus de clarté.",
  },
  "tucana": {
    pt: "Hoje, Tucana pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Tucana can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Tucana puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Tucana peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
  "ursa_major": {
    pt: "Hoje, Ursa Major pode servir apenas como um ponto de contemplação. Aquilo que atravessaste não é o céu inteiro; é apenas uma parte da forma que tens neste momento.",
    en: "Today, Ursa Major can simply serve as a point of contemplation. What you have been through is not the whole sky; it is only one part of the shape you hold right now.",
    es: "Hoy, Ursa Major puede servir simplemente como un punto de contemplación. Lo que has atravesado no es todo el cielo; es solo una parte de la forma que tienes en este momento.",
    fr: "Aujourd’hui, Ursa Major peut simplement servir de point de contemplation. Ce que tu as traversé n’est pas tout le ciel ; ce n’est qu’une partie de la forme que tu portes en ce moment.",
  },
  "ursa_minor": {
    pt: "Hoje, Ursa Minor pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Ursa Minor can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Ursa Minor puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Ursa Minor peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "vela": {
    pt: "Hoje, Vela pode servir apenas como um ponto de contemplação. Quando não vês o caminho inteiro, procura apenas aquilo que te pode orientar no próximo passo.",
    en: "Today, Vela can simply serve as a point of contemplation. When you cannot see the whole path, look only for what can guide your next step.",
    es: "Hoy, Vela puede servir simplemente como un punto de contemplación. Cuando no puedas ver todo el camino, busca solamente aquello que pueda orientarte en el siguiente paso.",
    fr: "Aujourd’hui, Vela peut simplement servir de point de contemplation. Quand tu ne vois pas tout le chemin, cherche simplement ce qui peut orienter ton prochain pas.",
  },
  "virgo": {
    pt: "Hoje, Virgo pode servir apenas como um ponto de contemplação. Recomeçar não precisa de apagar o que passou; pode ser uma forma de seguir com algo aprendido.",
    en: "Today, Virgo can simply serve as a point of contemplation. Beginning again does not have to erase what came before; it can mean moving forward with something learned.",
    es: "Hoy, Virgo puede servir simplemente como un punto de contemplación. Volver a empezar no tiene que borrar lo anterior; puede ser una forma de seguir con algo aprendido.",
    fr: "Aujourd’hui, Virgo peut simplement servir de point de contemplation. Recommencer n’a pas besoin d’effacer ce qui précède ; cela peut être une façon d’avancer avec ce que tu as appris.",
  },
  "volans": {
    pt: "Hoje, Volans pode servir apenas como um ponto de contemplação. Talvez hoje não seja preciso fechar uma conclusão; podes deixar algum espaço para o que ainda está a formar-se.",
    en: "Today, Volans can simply serve as a point of contemplation. Perhaps today does not need a final conclusion; you can leave some space for what is still taking shape.",
    es: "Hoy, Volans puede servir simplemente como un punto de contemplación. Quizá hoy no necesites cerrar una conclusión; puedes dejar espacio para lo que todavía está tomando forma.",
    fr: "Aujourd’hui, Volans peut simplement servir de point de contemplation. Peut-être qu’aujourd’hui n’a pas besoin d’une conclusion définitive ; tu peux laisser de la place à ce qui prend encore forme.",
  },
  "vulpecula": {
    pt: "Hoje, Vulpecula pode servir apenas como um ponto de contemplação. Não precisas de saber já a resposta; às vezes, uma boa pergunta é suficiente para abrir espaço.",
    en: "Today, Vulpecula can simply serve as a point of contemplation. You do not need to know the answer yet; sometimes a good question is enough to create space.",
    es: "Hoy, Vulpecula puede servir simplemente como un punto de contemplación. No necesitas saber todavía la respuesta; a veces una buena pregunta basta para abrir espacio.",
    fr: "Aujourd’hui, Vulpecula peut simplement servir de point de contemplation. Tu n’as pas besoin de connaître déjà la réponse ; parfois, une bonne question suffit à ouvrir un espace.",
  },
};

export function getConstellationReflection(
  id: string,
  language: ConstellationReflectionLanguage
) {
  return CONSTELLATION_REFLECTIONS[id]?.[language] ?? "";
}
